PayrollSys/Models/ViewModel/Payslip.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PayrollSys.Models.ViewModel
{
    public class Payslip
    {
        [Required]
        public int SalaryId { get; set; }

        [DisplayName("Employee")]
        [Required]
        public string emp { get; set; }

        [DisplayName("Bonus")]
        public double bamount { get; set; }

        [DisplayName("Allowance")]
        public double aamount { get; set; }

        [DisplayName("Deduct")]
        public double damount { get; set; }

        [DisplayName("Month")]
        [Required]
        public string ym { get; set; }

        [DisplayName("EPF")]
        public double epf { get; set; }

        [DisplayName("Socso")]
        public double socso { get; set; }

        [DisplayName("Gross Salary")]
        [Required]
        public double grossSalary { get; set; }

        [DisplayName("Net Salary")]
        [Required]
        public double netSalary { get; set; }

        public List<avalue> avalue { get; set; }

        public List<bvalue> bvalue { get; set; }

        public List<dvalue> dvalue { get; set; }

        [NotMapped]
        public Position positions { get; set; }

        [NotMapped]
        public Employee employee { get; set; }

        public List<Allowance> allowance { get; set; }

        [NotMapped]
        public List<Bonus> bonus { get; set; }

        [NotMapped]
        public List<Deduct> deduct { get; set; }

        public double earning { get; set; }

        public double ded { get; set; }

    }
}

PayrollSys/Controllers/PayslipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PayrollSys.Models;
using PayrollSys.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PayrollSys.Models.ViewModel;
using Microsoft.AspNetCore.Routing;
using System.Security.Cryptography.X509Certificates;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using SelectPdf;
using System.IO;
using System.Net.Mail;
using System.Net;

namespace PayrollSys.Controllers
{
    public class PayslipController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PayslipController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var salary=_context.Salary.ToList();
            foreach (var item in salary)
            {
                Models.Employee ppl = _context.employees.Where(x => x.Email == item.emp).First();
                if (ppl == null)
                {
                    return RedirectToAction("Index");
                }
                item.employee = ppl;
                Models.Position post = _context.positions.Where(x => x.id == ppl.PositionID).First();
                item.positions = post;
            }
            return View("~/Views/Admin/Payslip/Index.cshtml",salary);
        }

        [HttpPost]
        public ActionResult Index(string month)
        {
            var sal = _context.Salary.Where(x => x.ym == month).ToList();
            foreach (var item in sal)
            {
                Models.Employee ppl = _context.employees.Where(x => x.Email == item.emp).First();
                if (ppl == null)
                {
                    return RedirectToAction("Index");
                }
                item.employee = ppl;
                Models.Position post = _context.positions.Where(x => x.id == ppl.PositionID).First();
                item.positions = post;
            }
            return View("~/Views/Admin/Payslip/Index.cshtml", sal);
        }

        [HttpGet]
        public ActionResult Payslip(int id)
        {
            
            Payslip sal = new Payslip();
            List<Allowance> alc = new List<Allowance>();
            List<Bonus> blc = new List<Bonus>();
            List<Deduct> dlc = new List<Deduct>();
            var salary = _context.Salary.Where(x => x.SalaryId == id).First();

            // Get value from avalue
            var a = _context.avalue.Where(x => x.salaryId == id).ToList();
            foreach (var item in a)
            {
                Allowance all = _context.Allowance.Where(x => x.AllowanceId == item.allowanceId).First();
                alc.Add(new Allowance() { AllowanceId = all.AllowanceId, criteria=all.criteria, rate=all.rate });
                
            }
            sal.allowance = alc;

            // Get value from bvalue
            var b = _context.bvalue.Where(x => x.salaryId == id).ToList();
            double brate = 0;
            foreach (var item in b)
            {
                Bonus bn = _context.Bonus.Where(x => x.BonusId == item.bonusId).First();
                brate = 0;
                brate = Math.Round(bn.rate / 100 * salary.grossSalary,2);
                blc.Add(new Bonus() { BonusId = bn.BonusId, criteria = bn.criteria, rate = brate });
                 
            }
            sal.bonus = blc;

            // Get value from dvalue
            var d = _context.dvalue.Where(x => x.salaryId == id).ToList();
            foreach (var item in d)
            {
                Deduct dec = _context.Deduct.Where(x => x.DeductId == item.deductId).First();
                
                if (item.deductId == 1)
                {
                    //calculate adsent day
                    var at = _context.attendance.Where(x => x.emp == salary.emp && x.Month == salary.ym).ToList();
                    int counter = 0;
                    foreach (var day in at)
                    {
                       if (day.Status == "Absent")
                       {
                           counter++;
                       }
                    }

                    if (counter > 0)
                    {
                        double absent = 0;
                        absent = Math.Round(salary.grossSalary / dec.rate * counter,2);
                        dlc.Add(new Deduct() { DeductId = dec.DeductId, criteria = dec.criteria, rate = absent });
                    }

                }
                else if (item.deductId == 2)
                {
                   // verify got request advance
                   var av = _context.advances.Where(x => x.employeeName == salary.emp && x.ym == salary.ym).ToList();
                   foreach (var advance in av)
                   {
                      if (advance.status == "Approved")
                      {
                         double dv = 0;
                         dv = Math.Round(salary.grossSalary * dec.rate / 100,2);
                         dlc.Add(new Deduct() { DeductId = dec.DeductId, criteria = dec.criteria, rate = dv });
                      }
                   }

                }
                else
                {
                    double dv = 0;
                    dv = Math.Round(salary.grossSalary * dec.rate / 100,2);
                    dlc.Add(new Deduct() { DeductId = dec.DeductId, criteria = dec.criteria, rate = dv });
                }
            }

            sal.deduct = dlc;

            var e = _context.evalue.Where(x => x.salaryId == id).ToList();
            var f = _context.svalue.Where(x => x.salaryId == id).ToList();
            sal.emp = salary.emp;
            sal.ym = salary.ym;
            sal.aamount = salary.aamount;
            sal.avalue = a;
            sal.bamount = salary.bamount;
            sal.bvalue = b;
            sal.damount = salary.damount;
            sal.dvalue = d;
            sal.epf = salary.epf;
            sal.socso = salary.socso;
            sal.grossSalary = salary.grossSalary;
            sal.netSalary = salary.netSalary;

            sal.earning = Math.Round(salary.aamount + salary.bamount + salary.grossSalary,2);
            sal.ded = Math.Round(salary.epf + salary.socso + salary.damount,2);

            Employee ppl = _context.employees.Where(x => x.Email == salary.emp).First();
            sal.employee = ppl;
            Position post = _context.positions.Where(x => x.id == ppl.PositionID).First();
            sal.positions = post;

            return View("~/Views/Admin/Payslip/slip.cshtml", sal);
        }

        public ActionResult Pdf(Payslip model)
        {
            var ym = model.ym;
            var id = model.employee.Id;
            var name = model.employee.fullName;
            var ic = model.employee.ICNo;
            var ph = model.employee.PhoneNo;
            var position = model.positions.job;
            var email = model.emp;
            var gs = model.grossSalary;
            List<Allowance> all = model.allowance;
            List<Bonus> bn = model.bonus;
            List<Deduct> ded = model.deduct;
            var epf = model.epf;
            var socso = model.socso;
            var earn = model.earning;
            var deduct = model.ded;
            var net = model.netSalary;

            string ca = "";
            if (all!=null)
            {
                ca = "<tr><th class='col-sm-12'>Allowance</th></tr>";
                foreach (var item in all)
                {
                    ca += "<tr><td class='col-sm-8'>"+item.criteria+"</td><td class='col-sm-4'>"+ item.rate+"</td></tr>";
                    
                }

            }

            
            var cb = "";
            if (bn!= null)
            {
                 cb = " <tr><th class='col-sm-12'>Bonus</th></tr>";
                 foreach(var item in bn)
                 {
                    
                    cb += "<tr><td class='col-sm-8'>"+item.criteria+"</td><td class='col-sm-4'>" +
                            item.rate+ "</td></tr>";
                 }
            }

            var cd = "";
            if (ded!= null)
            {
                foreach (var item in ded)
                {
                    cd += "<tr><td class='col-sm-8'>" + item.criteria + "</td>" +
                        "<td class='col-sm-4'>" + item.rate + "</td></tr>";

                }
            }


            var HtmlString = "<!DOCTYPE html><html lang='en'><head><meta charset = 'utf-8' /><meta name = 'viewport' content = 'width=device-width, initial-scale=1.0' />" +
                             "<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' integrity='sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk' crossorigin='anonymous'></ head >" +
                             "<div class='card'><div class='card-body'><center><h2>V3X Malaysia Sdn Bhd</h2><p>VISION, VIRTUAL AND VISUALIZATION</p>" +
                             "<h5>Payslip for the period of " + ym + "</h5></center><div class='row'><div class='col-sm-3'>Employee Id</div>" +
                             "<div class='col-sm-3'>: " + id + "</div><div class='col-sm-3'>Name</div>" +
                             "<div class='col-sm-3'>: " + name + "</div></div><div class='row'><div class='col-sm-3'>IC</div>" +
                             "<div class='col-sm-3'>: " + ic + "</div><div class='col-sm-3'>Contact Number</div>" +
                             "<div class='col-sm-3'>: " + ph + "</div></div><div class='row'><div class='col-sm-3'>Position</div>" +
                             "<div class='col-sm-3'>: " + position + "</div><div class='col-sm-3'>Email</div>" +

PayrollSys/Views/Admin/Payslip/Index.cshtml
@model IEnumerable<PayrollSys.Models.Salary>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<center>
    <h1>Payslip</h1>
    <hr />
    @using (Html.BeginForm("Index","Payslip",FormMethod.Post))
    {
        <span>Month :</span>
        <input type="month" name="month" />
        <input type="submit" value="Search" />
    }
</center>
<br />

<table class="table table-sm table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.emp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bamount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.aamount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.damount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ym)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.epf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.socso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.grossSalary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.netSalary)
            </th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.employee.fullName
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bamount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.aamount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.damount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ym)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.epf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.socso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.grossSalary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.netSalary)
            </td>

            <td>
                <a asp-action="Payslip" asp-route-id="@item.SalaryId">Payslip</a>
            </td>
        </tr>
}
    </tbody>
</table>

<a asp-action="Index" asp-controller="Admin" class="btn btn-primary">
    <svg class="bi bi-arrow-left-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
        <path fill-rule="evenodd" d="M8.354 11.354a.5.5 0 0 0 0-.708L5.707 8l2.647-2.646a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708 0z" />
        <path fill-rule="evenodd" d="M11.5 8a.5.5 0 0 0-.5-.5H6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5z" />
    </svg>
    Back
</a>

PayrollSys/Views/Admin/Payslip/slip.cshtml
@model PayrollSys.Models.ViewModel.Payslip

@{
    ViewData["Title"] = "slip";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<div class="row">
    <div class="col-sm-10"><p>Payslip</p></div>
    <div class="col-sm-1">
        <form asp-action="Pdf">
            @Html.HiddenFor(model => model.ym)
            @Html.HiddenFor(model => model.employee.Id)
            @Html.HiddenFor(model => model.employee.fullName)
            @Html.HiddenFor(model => model.employee.ICNo)
            @Html.HiddenFor(model => model.employee.PhoneNo)
            @Html.HiddenFor(model => model.positions.job)
            @Html.HiddenFor(model => model.emp)
            @Html.HiddenFor(model => model.grossSalary)
            @if (Model.allowance.Count != 0)
            {@for (int i = 0; i < Model.allowance.Count; i++)
            {@Html.HiddenFor(it => Model.allowance[i].criteria)
             @Html.HiddenFor(it => Model.allowance[i].rate)
            }
            }
            @if (Model.bonus.Count != 0)
            {@for (int i = 0; i < Model.bonus.Count; i++)
            {@Html.HiddenFor(it => Model.bonus[i].criteria)
             @Html.HiddenFor(it => Model.bonus[i].rate)
            }
            }
            @if (Model.deduct.Count != 0)
            {@for (int i = 0; i < Model.deduct.Count; i++)
            {@Html.HiddenFor(it => Model.deduct[i].criteria)
             @Html.HiddenFor(it => Model.deduct[i].rate)
            }
            }
            @Html.HiddenFor(model => model.epf)
            @Html.HiddenFor(model => model.socso)
            @Html.HiddenFor(model => model.earning)
            @Html.HiddenFor(model => model.ded)
            @Html.HiddenFor(model => model.netSalary)
            <button type="submit" class="btn " data-toggle="tooltip" title="PDF"><span class="material-icons">print</span></button>
        </form>
    </div>
    <div class="col-sm-1">
        <form asp-action="Email">
            @Html.HiddenFor(model => model.ym)
            @Html.HiddenFor(model => model.employee.Id)
            @Html.HiddenFor(model => model.employee.fullName)
            @Html.HiddenFor(model => model.employee.ICNo)
            @Html.HiddenFor(model => model.employee.PhoneNo)
            @Html.HiddenFor(model => model.positions.job)
            @Html.HiddenFor(model => model.emp)
            @Html.HiddenFor(model => model.grossSalary)
            @if (Model.allowance.Count != 0)
            {@for (int i = 0; i < Model.allowance.Count; i++)
            {@Html.HiddenFor(it => Model.allowance[i].criteria)
             @Html.HiddenFor(it => Model.allowance[i].rate)
            }
            }
            @if (Model.bonus.Count != 0)
            {@for (int i = 0; i < Model.bonus.Count; i++)
            {@Html.HiddenFor(it => Model.bonus[i].criteria)
             @Html.HiddenFor(it => Model.bonus[i].rate)
            }
            }
            @if (Model.deduct.Count != 0)
            {@for (int i = 0; i < Model.deduct.Count; i++)
            {@Html.HiddenFor(it => Model.deduct[i].criteria)
             @Html.HiddenFor(it => Model.deduct[i].rate)
            }
            }
            @Html.HiddenFor(model => model.epf)
            @Html.HiddenFor(model => model.socso)
            @Html.HiddenFor(model => model.earning)
            @Html.HiddenFor(model => model.ded)
            @Html.HiddenFor(model => model.netSalary)
            <button type="submit" class="btn " data-toggle="tooltip" title="Email the payslip"><span class="material-icons">email</span></button>
        </form>
    </div>
</div>
<br />
<div class="card">
    <div class="card-body">
        <center>
            <h2>V3X Malaysia Sdn Bhd</h2>
            <p>VISION, VIRTUAL AND VISUALIZATION</p>
            <h5>Payslip for the period of @Html.DisplayFor(model => model.ym)</h5>
        </center>
        <div class="row">
            <div class="col-sm-3">Employee Id</div>
            <div class="col-sm-3">: @Html.DisplayFor(model => model.employee.Id)</div>
            <div class="col-sm-3">Name</div>
            <div class="col-sm-3">: @Html.DisplayFor(model => model.employee.fullName)</div>
        </div>
        <div class="row">
            <div class="col-sm-3">IC</div>
            <div class="col-sm-3">: @Html.DisplayFor(model => model.employee.ICNo)</div>
            <div class="col-sm-3">Contact Number</div>
            <div class="col-sm-3">: @Html.DisplayFor(model => model.employee.PhoneNo)</div>
        </div>
        <div class="row">
            <div class="col-sm-3">Position</div>
            <div class="col-sm-3">: @Html.DisplayFor(model => model.positions.job)</div>
            <div class="col-sm-3">Email</div>
            <div class="col-sm-3">: @Html.DisplayFor(model => model.emp)</div>
        </div>

        <br />

        <div class="row">

            <div class="col-sm-6 border">
                <table>
                    <tr>
                        <th class="col-sm-8">Earnings</th>
                        <th class="col-sm-4">Amount</th>
                    </tr>

                </table>
            </div>
            <div class="col-sm-6 border">
                <table>
                    <tr>
                        <th class="col-sm-8">Deductions</th>
                        <th class="col-sm-4">Amount</th>
                    </tr>

                </table>
            </div>

        </div>

        <div class="row">
            <div class="col-sm-6 border">
                <table>
                    <tr>
                        <td class="col-sm-8">Basic Salary</td>
                        <td class="col-sm-4">@Html.DisplayFor(model => model.grossSalary)</td>
                    </tr>
                    @if (Model.allowance.Count != 0)
                    {
                        <tr>
                            <th class="col-sm-12">Allowance</th>
                        </tr>
                        @for (int i = 0; i < Model.allowance.Count; i++)
                        {
                            <tr>
                                <td class="col-sm-8">@Html.DisplayFor(it => Model.allowance[i].criteria)</td>
                                <td class="col-sm-4">@Html.DisplayFor(it => Model.allowance[i].rate)</td>
                            </tr>

                        }
                    }
                    @if (Model.bonus.Count != 0)
                    {
                        <tr>
                            <th class="col-sm-12">Bonus</th>
                        </tr>
                        @for (int i = 0; i < Model.bonus.Count; i++)
                        {
                            <tr>
                                <td class="col-sm-8">@Html.DisplayFor(it => Model.bonus[i].criteria)</td>
                                <td class="col-sm-4">@Html.DisplayFor(it => Model.bonus[i].rate)</td>
                            </tr>

                        }
                    }
                </table>
            </div>
            <div class="col-sm-6 border">
                <table>
                    @if (Model.deduct.Count != 0)
                    {
                        @for (int i = 0; i < Model.deduct.Count; i++)
                        {
                            <tr>
                                <td class="col-sm-8">@Html.DisplayFor(it => Model.deduct[i].criteria)</td>
                                <td class="col-sm-4">@Html.DisplayFor(it => Model.deduct[i].rate)</td>
                            </tr>

                        }
                    }
                    <tr>
                        <th class="col-sm-12">Government Payment</th>
                    </tr>
                    <tr>
                        <td class="col-sm-8">EPF</td>
                        <td class="col-sm-4">@Html.DisplayFor(model => model.epf)</td>
                    </tr>
                    <tr>
                        <td class="col-sm-8">Socso</td>
                        <td class="col-sm-4">@Html.DisplayFor(model => model.socso)</td>
                    </tr>


                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6 border">
                <table>
                    <tr>
                        <td class="col-sm-8">Total Earnings</td>
                        <td class="col-sm-4">@Html.DisplayFor(model => model.earning)</td>
                    </tr>
                </table>
            </div>
            <div class="col-sm-6 border">
                <table>
                    <tr>
                        <td class="col-sm-8">Total Deductions</td>
                        <td class="col-sm-4">@Html.DisplayFor(model => model.ded)</td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="row border bg-light">
            <div class="col-sm-6 "></div>
            <div class="col-sm-6 ">
                <table>
                    <tr>
                        <td class="col-sm-8">Net Pay</td>
                        <td class="col-sm-4">@Html.DisplayFor(model => model.netSalary)</td>
                    </tr>
                </table>
            </div>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-lg-3">_____________________________</div>
            <div class="col-lg-6"></div>
            <div class="col-lg-3">_____________________________</div>
        </div>
        <div class="row">
            <div class="col-lg-3">Employer's Signature</div>
            <div class="col-lg-6"></div>
            <div class="col-lg-3">Employee's Signature</div>
        </div>

    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn btn-primary">
        <svg class="bi bi-arrow-left-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path fill-rule="evenodd" d="M8.354 11.354a.5.5 0 0 0 0-.708L5.707 8l2.647-2.646a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708 0z" />
            <path fill-rule="evenodd" d="M11.5 8a.5.5 0 0 0-.5-.5H6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5z" />
        </svg>
        Back
    </a>
</div>